sudo: required
services:
  - docker

before_install: 
  - docker build -t mrnothing01/test-app -f ./app/Dockerfile.dev .

script: 
  - docker run -e CI=true mrnothing01/test-app python -m coverage run -m pytest

after_success: 
  - docker build -t mrnothing01/multi-app -f Dockerfile ./app
  - docker build -t hafimrnothing01z/multi-nginx -f Dockerfile ./nginx
  - docker build -t hafmrnothing01iz/multi-web -f Dockerfile ./web
  # Login to docker CLI
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_NAME" --password-stdin
  - docker push hafmrnothing01iz/multi-app
  - docker push hafmrnothing01iz/multi-nginx
  - docker push hafmrnothing01iz/multi-web


