sudo: required
services:
  - docker

before_install: 
  - docker build -t hafiz/test-app -f Dockerfile.dev ./app

script: 
  - docker run -e CI=true hafiz/test-app python -m coverage run -m pytest

after_success: 
  - docker build -t hafiz/multi-app -f Dockerfile ./app
  - docker build -t hafiz/multi-nginx -f Dockerfile.nginx ./nginx
  - docker build -t hafiz/multi-web -f Dockerfile.web ./web



