sudo: required
services:
  - docker

before_install: 
  - docker build -t hafiz/docker-fastapi-redis -f Dockerfile.dev .

script: 
  - docker run -e CI=true hafiz/docker-fastapi-redis python -m coverage run -m pytest
