sudo: required
services:
  - docker

before_install: 
  - docker build -t mrnothing01/test-app -f Dockerfile.dev ./app

script: 
  - docker run -e CI=true mrnothing01/test-app python -m coverage run -m pytest

after_success: 
  - docker build -t hafiz/multi-app -f Dockerfile ./app
  - docker build -t hafiz/multi-nginx -f Dockerfile ./nginx
  - docker build -t hafiz/multi-web -f Dockerfile ./web
  # Login to docker CLI
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_NAME" --password-stdin
  - docker push hafiz/multi-app
  - docker push hafiz/multi-nginx
  - docker push hafiz/multi-web


