version: '3'

services:
  redis-server:
    image: 'redis'

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    depends_on:
      - redis-server
    
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/code/app
    depends_on:
      - redis-server
      - api
    command: ["ptw"]