FROM python:3.11-alpine

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app
RUN coverage run -m pytest
RUN coverage report -m


CMD ["fastapi", "run", "app/main.py", "--port", "8000", "--reload"]