FROM python:3.11-alpine
EXPOSE 80

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code/app
RUN coverage run -m pytest
RUN coverage report -m


CMD ["fastapi", "run", "app/main.py","--reload"]